// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHGMmdKterDplh2G_GOycIhwRSsnjwsTk',
    appId: '1:595543877683:web:c109399780b2691bd59b46',
    messagingSenderId: '595543877683',
    projectId: 'nizam-mohasebi',
    authDomain: 'nizam-mohasebi.firebaseapp.com',
    storageBucket: 'nizam-mohasebi.firebasestorage.app',
    measurementId: 'G-M4V75STK9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSGGbgwq5nxRLdbaGVU7BNfpORiF8Da-E',
    appId: '1:595543877683:android:c05f3c97f671d0f2d59b46',
    messagingSenderId: '595543877683',
    projectId: 'nizam-mohasebi',
    storageBucket: 'nizam-mohasebi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9_ZDi5Ryj7m68OCVac0CK2FpiJuim2z0',
    appId: '1:595543877683:ios:86595013e812c92bd59b46',
    messagingSenderId: '595543877683',
    projectId: 'nizam-mohasebi',
    storageBucket: 'nizam-mohasebi.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9_ZDi5Ryj7m68OCVac0CK2FpiJuim2z0',
    appId: '1:595543877683:ios:86595013e812c92bd59b46',
    messagingSenderId: '595543877683',
    projectId: 'nizam-mohasebi',
    storageBucket: 'nizam-mohasebi.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHGMmdKterDplh2G_GOycIhwRSsnjwsTk',
    appId: '1:595543877683:web:3b2da798cdba558cd59b46',
    messagingSenderId: '595543877683',
    projectId: 'nizam-mohasebi',
    authDomain: 'nizam-mohasebi.firebaseapp.com',
    storageBucket: 'nizam-mohasebi.firebasestorage.app',
    measurementId: 'G-YEPBSMP1QG',
  );
}